# Generated by Django 3.1.3 on 2020-11-02 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
    ]
